# Generated by Django 4.0.5 on 2022-07-19 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animalApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliment',
            name='suppliment_name',
            field=models.CharField(blank=True, db_column='suppliment_name', max_length=25, null=True, unique=True, verbose_name='supplement Name'),
        ),
        migrations.AddField(
            model_name='suppliment',
            name='suppliment_production_added',
            field=models.FloatField(blank=True, db_column='suppliment_production_added', default=0.0, verbose_name='Production Added'),
        ),
        migrations.AddField(
            model_name='suppliment',
            name='suppliment_production_after',
            field=models.FloatField(db_column='suppliment_production_after', default=0.0, verbose_name='Production After Suppliment'),
        ),
        migrations.AddField(
            model_name='suppliment',
            name='suppliment_production_before',
            field=models.FloatField(db_column='suppliment_production_before', default=0.0, verbose_name='Production Before Suppliment'),
        ),
        migrations.AddField(
            model_name='suppliment',
            name='suppliment_production_id',
            field=models.ForeignKey(db_column='suppliment_production_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='animalApp.milk_production', verbose_name='Production Id'),
        ),
    ]
