# Generated by Django 4.0.5 on 2022-07-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalApp', '0002_suppliment_suppliment_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milk_production',
            options={'ordering': ('-production_id',)},
        ),
        migrations.AlterModelOptions(
            name='suppliment',
            options={'ordering': ('suppliment_animal_id',)},
        ),
        migrations.AlterField(
            model_name='suppliment',
            name='suppliment_name',
            field=models.CharField(blank=True, db_column='suppliment_name', max_length=25, null=True, verbose_name='supplement Name'),
        ),
    ]
