# Generated by Django 4.0.5 on 2022-07-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalApp', '0003_alter_milk_production_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet_visist_prescription',
            name='prescription_disease_name',
            field=models.CharField(db_column='prescription_disease_name', default='', max_length=30, verbose_name='Disease Name'),
        ),
    ]
